[project]
name = "cesarcardoso-cc"
version = "0.3.0"
description = "Markdown to HTML of cesarcardoso.cc"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "markdown>=3.10",
    "qrcode[pil]>=8.2",
    "requests>=2.32.5",
]

[tool.bumpversion]
tag = true
tag_name = "v{new_version}"
pre_commit_hooks = ["uvx black main.py", "uvx isort main.py", "git add .", "uv sync --upgrade", "git add uv.lock"]
commit = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
