[project]
name = "cesarcardoso-cc"
version = "0.1.0"
description = "Markdown to HTML of cesarcardoso.cc"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "markdown>=3.10",
    "qrcode[pil]>=8.2",
]

[tool.bumpversion]
tag = true
tag_name = "v{new_version}"
pre_commit_hooks = ["uv sync --upgrade", "git add uv.lock"]
commit = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
